// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package ev24.protobuf.example;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ev24_protobuf_example_ExampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ev24_protobuf_example_ExampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ev24_protobuf_example_ExampleRequest_PayloadEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ev24_protobuf_example_ExampleRequest_PayloadEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ev24_protobuf_example_ExampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ev24_protobuf_example_ExampleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ev24_protobuf_example_ExampleResponse_PayloadEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ev24_protobuf_example_ExampleResponse_PayloadEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\025ev24.protobuf.example\"\256" +
      "\001\n\016ExampleRequest\022\036\n\nrequest_id\030\001 \001(\tR\nr" +
      "equest_id\022L\n\007payload\030\002 \003(\01322.ev24.protob" +
      "uf.example.ExampleRequest.PayloadEntryR\007" +
      "payload\032.\n\014PayloadEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\"\260\001\n\017ExampleResponse\022\036\n\nr" +
      "equest_id\030\001 \001(\tR\nrequest_id\022M\n\007payload\030\002" +
      " \003(\01323.ev24.protobuf.example.ExampleResp" +
      "onse.PayloadEntryR\007payload\032.\n\014PayloadEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012i\n\016Ex" +
      "ampleService\022W\n\006handle\022%.ev24.protobuf.e" +
      "xample.ExampleRequest\032&.ev24.protobuf.ex" +
      "ample.ExampleResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ev24_protobuf_example_ExampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ev24_protobuf_example_ExampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ev24_protobuf_example_ExampleRequest_descriptor,
        new java.lang.String[] { "RequestId", "Payload", });
    internal_static_ev24_protobuf_example_ExampleRequest_PayloadEntry_descriptor =
      internal_static_ev24_protobuf_example_ExampleRequest_descriptor.getNestedTypes().get(0);
    internal_static_ev24_protobuf_example_ExampleRequest_PayloadEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ev24_protobuf_example_ExampleRequest_PayloadEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ev24_protobuf_example_ExampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ev24_protobuf_example_ExampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ev24_protobuf_example_ExampleResponse_descriptor,
        new java.lang.String[] { "RequestId", "Payload", });
    internal_static_ev24_protobuf_example_ExampleResponse_PayloadEntry_descriptor =
      internal_static_ev24_protobuf_example_ExampleResponse_descriptor.getNestedTypes().get(0);
    internal_static_ev24_protobuf_example_ExampleResponse_PayloadEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ev24_protobuf_example_ExampleResponse_PayloadEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
